config/routes.rb
Rails.application.routes.draw do
  #Home Routes
  root 'home#login'
  get '/home/load_partial', to: 'home#load_partial', :as => 'load_home_partial'
  get '/index', to: 'home#index', :as => 'index'

  #Admin Routes
  get '/admin/load_partial', to: 'admin#load_partial', :as => 'load_admin_partial'
  get '/admin/:id/edit', to: 'admin#edit', :as => 'admin_edit'
  patch '/admin/:id/update', to: 'admin#update', :as => 'admin_update'

  post '/login' => 'admin#login', :as => :admin_login
    controller :admin do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  #API Routes
  get '/articles_init/:locale' => 'api#articles_init'
  get '/events_init/:locale' => 'api#events_init'
  get '/products_init/:locale' => 'api#products_init'
  #get '/test_init/:locale' => 'api#test_init'

  #Article Routes
  get '/articles/load_partial', to: 'articles#load_partial', :as => 'load_article_partial'
  get '/articles/new', to: 'articles#new', :as => 'article_new'
  post '/articles/create', to: 'articles#create', :as => 'article_create'
  get '/articles/:id/destroy', to: 'articles#destroy',:as => 'article_destroy'
  get '/articles/:id/edit', to: 'articles#edit', :as => 'article_edit'
  patch '/articles/:id/update', to: 'articles#update', :as => 'article_update'

  #Events Routes
  get '/events/load_partial', to: 'events#load_partial', :as => 'load_event_partial'
  get '/events/new', to: 'events#new', :as => 'event_new'
  post '/events/create', to: 'events#create', :as => 'event_create'
  get '/events/:id/destroy', to: 'events#destroy',:as => 'event_destroy'
  get '/events/:id/edit', to: 'events#edit', :as => 'event_edit'
  patch '/events/:id/update', to: 'events#update', :as => 'event_update'

  #Products Routes
  get '/products/load_partial', to: 'products#load_partial', :as => 'load_product_partial'
  get '/products/new', to: 'products#new', :as => 'product_new'
  post '/products/create', to: 'products#create', :as => 'product_create'
  get '/products/:id/destroy', to: 'products#destroy',:as => 'product_destroy'
  get '/products/:id/edit', to: 'products#edit', :as => 'product_edit'
  patch '/products/:id/update', to: 'products#update', :as => 'product_update'
  put 'products/sort', to: 'products#sort', :as => 'products_sort'

  #Wines Routes
  get '/wines/load_partial', to: 'wines#load_partial', :as => 'load_wine_partial'
  get '/wines/new', to: 'wines#new', :as => 'wine_new'
  post '/wines/create', to: 'wines#create', :as => 'wine_create'
  get '/wines/:id/destroy', to: 'wines#destroy',:as => 'wine_destroy'
  get '/wines/:id/edit', to: 'wines#edit', :as => 'wine_edit'
  patch '/wines/:id/update', to: 'wines#update', :as => 'wine_update'
  put 'wines/sort', to: 'wines#sort', :as => 'wines_sort'

  #Services Routes
  get '/services/load_partial', to: 'services#load_partial', :as => 'load_service_partial'
  get '/services/new', to: 'services#new', :as => 'service_new'
  post '/services/create', to: 'services#create', :as => 'service_create'
  get '/services/:id/destroy', to: 'services#destroy',:as => 'service_destroy'
  get '/services/:id/edit', to: 'services#edit', :as => 'service_edit'
  patch '/services/:id/update', to: 'services#update', :as => 'service_update'
  put 'services/sort', to: 'services#sort', :as => 'services_sort'

  #Notifications Routes
  get '/notifications/load_partial', to: 'notifications#load_partial', :as => 'load_notification_partial'
  get '/notifications/new', to: 'notifications#new', :as => 'notification_new'
  post '/notifications/create', to: 'notifications#create', :as => 'notification_create'
  get '/notifications/:id/destroy', to: 'notifications#destroy',:as => 'notification_destroy'
  get '/notifications/:id/edit', to: 'notifications#edit', :as => 'notification_edit'
  patch '/notifications/:id/update', to: 'notifications#update', :as => 'notification_update'

end

app/models/product.rb
class Product < ApplicationRecord
	translates :title, :text
	globalize_accessors :locales => [:en, :de, :el], :attributes => [:title, :text]
	mount_uploader :image, ImageUploader
	#acts_as_sortable
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :set_product, only: [:edit, :update, :destroy]
	before_action :update_version, only: [:move, :create, :update, :delete_image]

	def load_partial
		@products = Product.all.order(position: :asc)
		#add_breadcrumb "Home", :root_path
	end

	def move
    	@product = Product.find(params[:id])
    	@product.move_to! params[:position]
  	end

  	def sort
	    params[:order].each do |key,value|
	      Product.find(value[:id]).update_attribute(:position,value[:position])
	    end
	    
	    render :nothing => true
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new(product_params)

		@admin = Admin.first
		@admin.increment(:products_last_position)
		@admin.save

		@empty_field_flag = false

		params[:product].values.each do |param|		
		  if !param.present?
		  	@empty_field_flag = true
		  end
		end

		if !@empty_field_flag
			if @product.save(product_params)		
				@products = Product.all.order(position: :asc) #needed to load product partial again
				respond_to do |format|
	   				format.js
				end
			end
		else
			respond_to do |format|
				format.js {render :action => 'required_fields'}
			end
		end			
	end

	def edit
		
	end

	def update
		@empty_field_flag = false

		params[:product].values.each do |param|		
		  if !param.present?
		  	@empty_field_flag = true
		  end
		end

		if !@empty_field_flag
			if @product.update(product_params)		
				@products = Product.all.order(position: :asc) #needed to load product partial again
				respond_to do |format|
	   				format.js
				end
			end
		else
			respond_to do |format|
				format.js {render :action => 'required_fields'}
			end
		end
	end

	def destroy
		@product.remove_image!
		if @product.destroy
			respond_to do |format|
				format.js
			end
		end
	end

	def update_version
		@admin = Admin.first
		@admin.increment(:version_number, by = 1)
		@admin.save 	
	end

	###############PRIVATE##################
	private

	def set_product
		@product = Product.find(params[:id])
		@products = Product.all.order(position: :asc)
	end

	def product_params
		if params[:product][:image].present?
			params.require(:product).permit(:id, :position, :image, *Product.globalize_attribute_names)
		else
			params.require(:product).permit(:id, :position, *Product.globalize_attribute_names)
		end
	end
	
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/modals/_createModal.html.erb
<div class="block">
  <div aria-hidden="false" data-backdrop="static" data-keyboard="false" style="display: block;" id="new_modal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="">
            <span>&times;</span>
          </button>
          <h5 class="">
            Add Product                
          </h5>
        </div>
        <%=form_for @product , url: product_create_path, remote: true, multipart: true, authenticity_token: true, html: {class: "form-horizontal"} do |f|%>
        <div class="modal-body with-padding" >          
          <h5>Upload Image: </h5>
          <%= f.file_field :image, :class => 'btn btn-default', 'data-show-upload' => false, :accept => 'image/*', :style=> 'width:100%;' %>
          <hr>
          <div class="tabbable">
            <ul class="nav nav-tabs">
              <% I18n.available_locales.map.with_index(1) do |locale, index| %>
              <li class="<%= index==1 ? 'active' : ' ' %>">
               <a href="#tab<%=locale%>" data-toggle="tab">
                 <h5>
                   <img src="assets/<%=I18n.t('language_name', locale: locale)%>_flag.png" style="width:20px; height: auto;"> 
                   <%= I18n.t('language_name', locale: locale) %>
                 </h5>
               </a>
             </li>
             <%end%>
           </ul>
           <%= f.number_field :position, :value=> Admin.first.products_last_position, :style=> 'display:none' %>
           <div class= "tab-content">           
            <% I18n.available_locales.map.with_index(1) do |locale, index| %>
            <div id='tab<%=locale%>' class='tab-pane fade in <%=index==1 ? 'active': ''%>'>                                        
              <h5> <%= I18n.t('language_name', locale: locale) %> Title: </h5>
              <%= f.text_field "title_#{locale}".to_sym,:class => 'form-control'%>
              <h5> <%= I18n.t('language_name', locale: locale) %> Text: </h5>
              <%= f.text_area "text_#{locale}".to_sym ,:style => "height: 150px;",:class => 'wysihtml5 editor wysihtml5-editor'%>
            </div>
            <%end%>
          </div>
        </div>
        <br>


      </div>
      <div class="modal-footer">
        <a class="btn btn-danger"  type="button" data-dismiss="modal">Close</a>
        <%= submit_tag "Save",:class => 'btn btn-success', :style=> "width:80px" , data: { disable_with: "Saving.." } %>
      </div>
    <% end %>

    </div>
    </div>
  </div>
</div>
<script>
  $('.wysihtml5').wysihtml5({
  toolbar: {
    "font-styles": false, // Font styling, e.g. h1, h2, etc.
    "emphasis": true, // Italics, bold, etc.
    "lists": false, // (Un)ordered lists, e.g. Bullets, Numbers.
    "html": false, // Button which allows you to edit the generated HTML.
    "link": false, // Button to insert a link.
    "image": false, // Button to insert an image.
    "color": false, // Button to change color of font
    "blockquote": false // Blockquote
    
  }
});
</script>

app/views/products/modals/_updateModal.html.erb
<div class="block">
  <div aria-hidden="false" data-backdrop="static" data-keyboard="false" style="display: block;" id="edit_modal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="">
            <span>&times;</span>
          </button>
          <h5 class="">
            Edit Product                
          </h5>
        </div>
        <%=form_for @product , url: product_update_path, remote: true, multipart: true, authenticity_token: true, html: {class: "form-horizontal"} do |f|%>
        <div class="modal-body with-padding" >          
          <h5>Change Image: </h5>
          <%= f.file_field :image, :class => 'btn btn-default', 'data-show-upload' => false, :accept => 'image/*', :style=> 'width:100%;' %>
          <hr>
          <div class="tabbable">
            <ul class="nav nav-tabs">
              <% I18n.available_locales.map.with_index(1) do |locale, index| %>
              <li class="<%= index==1 ? 'active' : ' ' %>">
               <a href="#tab<%=locale%>" data-toggle="tab">
                 <h5>
                   <img src="assets/<%=I18n.t('language_name', locale: locale)%>_flag.png" style="width:20px; height: auto;"> 
                   <%= I18n.t('language_name', locale: locale) %>
                 </h5>
               </a>
             </li>
             <%end%>
           </ul>
           <div class= "tab-content">           
            <% I18n.available_locales.map.with_index(1) do |locale, index| %>
            <div id='tab<%=locale%>' class='tab-pane fade in <%=index==1 ? 'active': ''%>'>                                         
              <h5> <%= I18n.t('language_name', locale: locale) %> Title: </h5>
              <%= f.text_field "title_#{locale}".to_sym,:class => 'form-control'%>
              <h5> <%= I18n.t('language_name', locale: locale) %> Text: </h5>
              <%= f.text_area "text_#{locale}".to_sym ,:style => "height: 150px;",:class => 'wysihtml5 editor wysihtml5-editor'%>
            </div>
            <%end%>
          </div>
        </div>
        <br>


      </div>
      <div class="modal-footer">
        <a class="btn btn-danger"  type="button" data-dismiss="modal">Close</a>
        <%= submit_tag "Save",:class => 'btn btn-success', :style=> "width:80px" , data: { disable_with: "Saving.." } %>
      </div>
    <% end %>

    </div>
    </div>
  </div>
</div>
<script>
  $('.wysihtml5').wysihtml5({
  toolbar: {
    "font-styles": false, // Font styling, e.g. h1, h2, etc.
    "emphasis": true, // Italics, bold, etc.
    "lists": false, // (Un)ordered lists, e.g. Bullets, Numbers.
    "html": false, // Button which allows you to edit the generated HTML.
    "link": false, // Button to insert a link.
    "image": false, // Button to insert an image.
    "color": false, // Button to change color of font
    "blockquote": false // Blockquote
    
  }
});
</script>