config/routes.rb
Rails.application.routes.draw do
  #Home Routes
  root 'home#login'
  get '/home/load_partial', to: 'home#load_partial', :as => 'load_home_partial'
  get '/index', to: 'home#index', :as => 'index'

  #Admin Routes
  get '/admin/load_partial', to: 'admin#load_partial', :as => 'load_admin_partial'
  get '/admin/:id/edit', to: 'admin#edit', :as => 'admin_edit'
  patch '/admin/:id/update', to: 'admin#update', :as => 'admin_update'

  post '/login' => 'admin#login', :as => :admin_login
    controller :admin do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  #API Routes
  get '/articles_init/:locale' => 'api#articles_init'
  get '/events_init/:locale' => 'api#events_init'
  get '/products_init/:locale' => 'api#products_init'
  #get '/test_init/:locale' => 'api#test_init'

  #Article Routes
  get '/articles/load_partial', to: 'articles#load_partial', :as => 'load_article_partial'
  get '/articles/new', to: 'articles#new', :as => 'article_new'
  post '/articles/create', to: 'articles#create', :as => 'article_create'
  get '/articles/:id/destroy', to: 'articles#destroy',:as => 'article_destroy'
  get '/articles/:id/edit', to: 'articles#edit', :as => 'article_edit'
  patch '/articles/:id/update', to: 'articles#update', :as => 'article_update'

  #Events Routes
  get '/events/load_partial', to: 'events#load_partial', :as => 'load_event_partial'
  get '/events/new', to: 'events#new', :as => 'event_new'
  post '/events/create', to: 'events#create', :as => 'event_create'
  get '/events/:id/destroy', to: 'events#destroy',:as => 'event_destroy'
  get '/events/:id/edit', to: 'events#edit', :as => 'event_edit'
  patch '/events/:id/update', to: 'events#update', :as => 'event_update'

  #Products Routes
  get '/products/load_partial', to: 'products#load_partial', :as => 'load_product_partial'
  get '/products/new', to: 'products#new', :as => 'product_new'
  post '/products/create', to: 'products#create', :as => 'product_create'
  get '/products/:id/destroy', to: 'products#destroy',:as => 'product_destroy'
  get '/products/:id/edit', to: 'products#edit', :as => 'product_edit'
  patch '/products/:id/update', to: 'products#update', :as => 'product_update'
  put 'products/sort', to: 'products#sort', :as => 'products_sort'

  #Wines Routes
  get '/wines/load_partial', to: 'wines#load_partial', :as => 'load_wine_partial'
  get '/wines/new', to: 'wines#new', :as => 'wine_new'
  post '/wines/create', to: 'wines#create', :as => 'wine_create'
  get '/wines/:id/destroy', to: 'wines#destroy',:as => 'wine_destroy'
  get '/wines/:id/edit', to: 'wines#edit', :as => 'wine_edit'
  patch '/wines/:id/update', to: 'wines#update', :as => 'wine_update'
  put 'wines/sort', to: 'wines#sort', :as => 'wines_sort'

  #Services Routes
  get '/services/load_partial', to: 'services#load_partial', :as => 'load_service_partial'
  get '/services/new', to: 'services#new', :as => 'service_new'
  post '/services/create', to: 'services#create', :as => 'service_create'
  get '/services/:id/destroy', to: 'services#destroy',:as => 'service_destroy'
  get '/services/:id/edit', to: 'services#edit', :as => 'service_edit'
  patch '/services/:id/update', to: 'services#update', :as => 'service_update'
  put 'services/sort', to: 'services#sort', :as => 'services_sort'

  #Notifications Routes
  get '/notifications/load_partial', to: 'notifications#load_partial', :as => 'load_notification_partial'
  get '/notifications/new', to: 'notifications#new', :as => 'notification_new'
  post '/notifications/create', to: 'notifications#create', :as => 'notification_create'
  get '/notifications/:id/destroy', to: 'notifications#destroy',:as => 'notification_destroy'
  get '/notifications/:id/edit', to: 'notifications#edit', :as => 'notification_edit'
  patch '/notifications/:id/update', to: 'notifications#update', :as => 'notification_update'

end

app/models/article.rb
class Article < ApplicationRecord
	translates :title, :text
	globalize_accessors :locales => [:en, :de, :el], :attributes => [:title, :text]
	mount_uploader :image, ImageUploader
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only: [:edit, :update, :destroy]

	def load_partial
		@articles = Article.all.order(created_at: :desc)
		#add_breadcrumb "Home", :root_path
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		@empty_field_flag = false

		params[:article].values.each do |param|
		  if !param.present?
		  	@empty_field_flag = true
		  end
		end

		if !@empty_field_flag
			if @article.save(article_params)
				@articles = Article.all #needed to load article partial again
				respond_to do |format|
	   				format.js
				end
			end
		else
			respond_to do |format|
				format.js {render :action => 'required_fields'}
			end
		end
	end

	def edit

	end

	def update
		@empty_field_flag = false

		params[:article].values.each do |param|
		  if !param.present?
		  	@empty_field_flag = true
		  end
		end

		if !@empty_field_flag
			if @article.update(article_params)
				@articles = Article.all #needed to load article partial again
				respond_to do |format|
	   				format.js
				end
			end
		else
			respond_to do |format|
				format.js {render :action => 'required_fields'}
			end
		end
	end

	def destroy
		@article.remove_image!
		if @article.destroy
			respond_to do |format|
				format.js
			end
		end
	end

	###############PRIVATE##################
	private

	def set_article
		@article = Article.find(params[:id])
		@articles = Article.all.order(:created_at)
	end

	def article_params
		if params[:article][:image].present?
			params.require(:article).permit(:id, :image, *Article.globalize_attribute_names)
		else
			params.require(:article).permit(:id, *Article.globalize_attribute_names)
		end
	end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div>
	<td>
		<% if article.image.blank?%>
			<img src="http://placehold.it/150x150?text=No+Image" style= "position:absolute">
		<%else%>
			<%= image_tag article.image_url(:large_thumb), :style => "position:absolute"%>
		<%end%>
	</td>
	<td>
		<div style=" margin-left:150px; min-height: 50px;" class="panel panel-default">
			<div class="tabbable">
				<div  class="panel-heading">
					<ul class="nav nav-tabs">
					<% I18n.available_locales.map.with_index(1) do |locale, index| %>
			          <li class="<%= index==1 ? 'active' : ' ' %>">
			            <a href="#tab_<%=article.class.name+article.id.to_s+"_"+locale.to_s%>" data-toggle="tab">
			              <img src="assets/<%=I18n.t('language_name', locale: locale)%>_flag.png" style="width:20px; height: auto;">
			              <%= I18n.t('language_name', locale: locale) %>
			            </a>
			          </li>
			        <%end%>
			        <span class="text-semibold pull-right" style="display: inline">
				        <%=link_to article_edit_path(article.id), :remote => true,:style=>"",:class => "btn btn-xs btn-success" do %>
				        	<i class="icon-pencil"></i>
				        <% end %>
				        <%=link_to article_destroy_path(article.id), :remote => true, :style=>"",:class => "btn btn-xs btn-danger", :data => {confirm: "Are you sure?"} do %>
				        	<i class="icon-close"></i>
				        <% end %>
					</span>
			        </ul>
				</div>
				<div class="panel-body ">
				    <div class= "tab-content">
		                <% I18n.available_locales.map.with_index(1) do |locale, index| %>
		                  <div id='tab_<%=article.class.name+article.id.to_s+"_"+locale.to_s%>' class='tab-pane fade in <%=index==1 ? 'active': ''%>'>
		                    <td style="height:5px" class="panel-heading">
		                    	<%= article.send("title_#{locale}") %>
		                    </td>
		                    <hr>
							<td style="">
								<%= article.send("text_#{locale}").html_safe %>
							</td>
		                    <br>
		                  </div>
		                <%end%>
             		</div>
				</div>
			</div>
		</div>
	</td>
</div>

app/views/articles/_articlePartial.html.erb
<%add_breadcrumb "Home"%>
<%add_breadcrumb "News"%>
<hr>
<div class="callout callout-success fade in">
	<h5>News</h5>
	<p>News Articles</p>
</div>
<div class="breadcrumb-line">
  <ul class="breadcrumb">
     <%= render_breadcrumbs :tag => :li, :separator => "" %>
  </ul>
  <div class="visible-xs breadcrumb-toggle">
    <a class="btn btn-link btn-lg btn-icon" data-toggle="collapse" data-target=".breadcrumb-buttons"><i class="icon-menu2"></i></a>
  </div>
  <ul class="breadcrumb-buttons collapse"></ul>
</div>
<div class="">
<%=	link_to "Add Article", {controller: 'articles', action: 'new'}, remote: true,
	 :class => "btn btn-lg btn-success btn-fill", :style=>"width:50%"%>
</div>
<hr>
<% if @articles.any? %>
<%= render @articles %>
<% else %>
	<p>No Articles yet.</p>
<% end %>

app/views/articles/create.js.erb
$('#new_modal').modal('toggle');

toastr.success('Saved successfully');

setTimeout(function(){
 $('.partial-container').html('<%= j(render partial: "/articles/articlePartial") %>')
}, 200)

app/views/articles/destroy.js.erb
toastr.info('Deleted successfully');

setTimeout(function(){
 $('.partial-container').html('<%= j(render partial: "/articles/articlePartial") %>')
}, 200)

app/views/articles/edit.js.erb
$('#modal-placeholder').html("");

$('#modal-placeholder').html("<%= escape_javascript render(:partial => 'articles/modals/updateModal') %>");

$('#edit_modal').modal('toggle');

app/views/articles/load_partial.js.erb
$('.partial-container').html('<%= j(render partial: "/articles/articlePartial") %>')

app/views/articles/new.js.erb
$('#modal-placeholder').html("");

$('#modal-placeholder').html("<%= escape_javascript render(:partial => 'articles/modals/createModal') %>");

$('#new_modal').modal('toggle');

app/views/articles/required_fields.js.erb
toastr.error('Please fill in the fields for every language');

app/views/articles/update.js.erb
$('#edit_modal').modal('toggle');

toastr.success('Saved successfully');

setTimeout(function(){
 $('.partial-container').html('<%= j(render partial: "/articles/articlePartial") %>')
}, 200)