config/routes.rb
Rails.application.routes.draw do
  #Home Routes
  root 'home#login'
  get '/home/load_partial', to: 'home#load_partial', :as => 'load_home_partial'
  get '/index', to: 'home#index', :as => 'index'

  #Admin Routes
  get '/admin/load_partial', to: 'admin#load_partial', :as => 'load_admin_partial'
  get '/admin/:id/edit', to: 'admin#edit', :as => 'admin_edit'
  patch '/admin/:id/update', to: 'admin#update', :as => 'admin_update'

  post '/login' => 'admin#login', :as => :admin_login
    controller :admin do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  #API Routes
  get '/articles_init/:locale' => 'api#articles_init'
  get '/events_init/:locale' => 'api#events_init'
  get '/products_init/:locale' => 'api#products_init'
  #get '/test_init/:locale' => 'api#test_init'

  #Article Routes
  get '/articles/load_partial', to: 'articles#load_partial', :as => 'load_article_partial'
  get '/articles/new', to: 'articles#new', :as => 'article_new'
  post '/articles/create', to: 'articles#create', :as => 'article_create'
  get '/articles/:id/destroy', to: 'articles#destroy',:as => 'article_destroy'
  get '/articles/:id/edit', to: 'articles#edit', :as => 'article_edit'
  patch '/articles/:id/update', to: 'articles#update', :as => 'article_update'

  #Events Routes
  get '/events/load_partial', to: 'events#load_partial', :as => 'load_event_partial'
  get '/events/new', to: 'events#new', :as => 'event_new'
  post '/events/create', to: 'events#create', :as => 'event_create'
  get '/events/:id/destroy', to: 'events#destroy',:as => 'event_destroy'
  get '/events/:id/edit', to: 'events#edit', :as => 'event_edit'
  patch '/events/:id/update', to: 'events#update', :as => 'event_update'

  #Products Routes
  get '/products/load_partial', to: 'products#load_partial', :as => 'load_product_partial'
  get '/products/new', to: 'products#new', :as => 'product_new'
  post '/products/create', to: 'products#create', :as => 'product_create'
  get '/products/:id/destroy', to: 'products#destroy',:as => 'product_destroy'
  get '/products/:id/edit', to: 'products#edit', :as => 'product_edit'
  patch '/products/:id/update', to: 'products#update', :as => 'product_update'
  put 'products/sort', to: 'products#sort', :as => 'products_sort'

  #Wines Routes
  get '/wines/load_partial', to: 'wines#load_partial', :as => 'load_wine_partial'
  get '/wines/new', to: 'wines#new', :as => 'wine_new'
  post '/wines/create', to: 'wines#create', :as => 'wine_create'
  get '/wines/:id/destroy', to: 'wines#destroy',:as => 'wine_destroy'
  get '/wines/:id/edit', to: 'wines#edit', :as => 'wine_edit'
  patch '/wines/:id/update', to: 'wines#update', :as => 'wine_update'
  put 'wines/sort', to: 'wines#sort', :as => 'wines_sort'

  #Services Routes
  get '/services/load_partial', to: 'services#load_partial', :as => 'load_service_partial'
  get '/services/new', to: 'services#new', :as => 'service_new'
  post '/services/create', to: 'services#create', :as => 'service_create'
  get '/services/:id/destroy', to: 'services#destroy',:as => 'service_destroy'
  get '/services/:id/edit', to: 'services#edit', :as => 'service_edit'
  patch '/services/:id/update', to: 'services#update', :as => 'service_update'
  put 'services/sort', to: 'services#sort', :as => 'services_sort'

  #Notifications Routes
  get '/notifications/load_partial', to: 'notifications#load_partial', :as => 'load_notification_partial'
  get '/notifications/new', to: 'notifications#new', :as => 'notification_new'
  post '/notifications/create', to: 'notifications#create', :as => 'notification_create'
  get '/notifications/:id/destroy', to: 'notifications#destroy',:as => 'notification_destroy'
  get '/notifications/:id/edit', to: 'notifications#edit', :as => 'notification_edit'
  patch '/notifications/:id/update', to: 'notifications#update', :as => 'notification_update'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def load_partial
		#@article = Article.all.order(:created_at)
		add_breadcrumb "Home", :root_path
	end

	def index
		add_breadcrumb "Home", :root_path
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_homePartial.html.erb
<div class="page-header">
  <div class="page-title">
    <h3>Control Panel <small>Home</small></h3>
  </div>
  <div id="reportrange" class="range">
    <div class="visible-xs header-element-toggle">
      <a class="btn btn-primary btn-icon"><i class="icon-calendar"></i></a>
    </div>
    
  </div>
</div>
<!-- Breadcrumbs line -->

<div class="breadcrumb-line">
  <ul class="breadcrumb">
     <%= render_breadcrumbs :tag => :li, :separator => "" %>
  </ul>
  <div class="visible-xs breadcrumb-toggle">
    <a class="btn btn-link btn-lg btn-icon" data-toggle="collapse" data-target=".breadcrumb-buttons"><i class="icon-menu2"></i></a>
  </div>

  <ul class="breadcrumb-buttons collapse"></ul>
</div>


<div class="callout callout-default fade in">
  <h5>Home</h5>
</div>
      <!-- /breadcrumbs line -->     

app/views/home/index.html.erb
<%if session[:admin]%>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1">
  <title>Rails Admin Panel</title>
  <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&amp;subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
  <%= content_for :header %>
</head>
<body>
  <!-- Navbar -->
  <div class="navbar navbar-inverse" role="navigation">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">My Admin Panel</a>
      <a class="sidebar-toggle"><i class="icon-paragraph-justify2"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-icons">
        <span class="sr-only">Toggle navbar</span>
        <i class="icon-grid3"></i>
      </button>
      <button type="button" class="navbar-toggle offcanvas">
        <span class="sr-only">Toggle navigation</span>
        <i class="icon-paragraph-justify2"></i>
      </button>
    </div>
    <ul class="nav navbar-nav navbar-right collapse" id="navbar-icons">
      <li>
      <%= button_to "Logout",  logout_path, :method => :delete, :class => "btn btn-lg btn-primary", :style=>"margin-top:8px;", :onclick => "return confirm('Are you sure you want to logout?')" %>
        </li>
    </ul>
  </div>
  <!-- /navbar -->
  <!-- Page container -->
  <div class="page-container">
    <!-- Sidebar -->
    <div class="sidebar">
      <div class="sidebar-content">
        <!-- User dropdown -->
        <div class="user-menu dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <img src="assets/app_logo.png" style="width:100%;height:100%;background-color:white;">
            <div class="user-info">
            </div>
          </a>
        </div>
        <!-- /user dropdown -->
        <!-- Main navigation -->
        <ul class="navigation">
          <li class="">
            <%= link_to load_home_partial_url, :remote => true do%>
                  <span>Home</span> <i class="icon-home"></i>
            <%end%>
          </li>
          <li class="">
            <%= link_to load_article_partial_url, :remote => true do%>
                  <span>News</span> <i class="icon-list2"></i>
            <%end%>
          </li>
          <li class="">
            <%= link_to load_event_partial_url, :remote => true do%>
                  <span>Events</span> <i class="icon-list2"></i>
            <%end%>
          </li>
          <li class="">
            <%= link_to load_product_partial_url, :remote => true do%>
                  <span>Products</span> <i class="icon-list2"></i>
            <%end%>
          </li>
          <li class="">
            <%= link_to load_notification_partial_url, :remote => true do%>
                  <span>Notifications</span> <i class="icon-list2"></i>
            <%end%>
          </li>
          <li class="">
            <%= link_to load_admin_partial_url, :remote => true do%>
                  <span>Profile</span> <i class="icon-list2"></i>
            <%end%>
          </li>
        </ul>
        <!-- /main navigation -->
      </div>
    </div>
    <!-- /sidebar -->
    <!-- Page content -->
    <div class="page-content">
      <!-- Page header -->
      <!-- /page header -->
      <!--Partial Container -->
      <div class="partial-container">
        <%= render :partial => 'homePartial'%>
      </div>
      <!-- /Partial Container -->
      <!-- /info blocks -->
      <!-- Footer -->
      <div class="footer clearfix">
        <div class="pull-right">Simple Rails Admin Panel, created by Tasos Anesiadis, find me on <a href="https://github.com/roneen31"> Github</a></div>
      </div>
      <!-- /footer -->
    </div>
    <!-- /page content -->
  </div>
  <!-- /page container -->
  <!-- Modal Placeholder -->
  <div id="modal-placeholder">
  </div>
  <!-- /Modal Placeholder -->
</body>
</html>
<%
else
  raise ActionController::RoutingError.new('Not Found')
end%>

app/views/home/load_partial.js.erb
$('.partial-container').html('<%= j(render partial: "/home/homePartial") %>')

app/views/home/login.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1">
<title>Simple Rails Admin Panel</title>
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&amp;subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
</head>

<body class="full-width page-condensed">
	<!-- Navbar -->
	<div class="navbar navbar-inverse" role="navigation">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-right">
				<span class="sr-only">Toggle navbar</span>
				<i class="icon-grid3"></i>
			</button>
			<a class="navbar-brand" href="#">Simple Rails Admin Panel</a>
		</div>
		<ul class="nav navbar-nav navbar-right collapse">

		</ul>
	</div>
	<!-- /navbar -->
	<!-- Login wrapper -->


	<div class="login-wrapper">
	<%= form_for(:admin,:remote => true, :html => {id: 'form-signin', class: 'form-signin'}, :url => 'login') do |f| %>

			<div class="popup-header">

				<span class="text-semibold">Administrator Login</span>

			</div>
			<div class="well">
				<div class="form-group has-feedback">
					<label>Username</label>
					<%= f.text_field :username, class: 'form-control',:html => { type:'text',  name: 'username', required: "", autofocus: ""}, :placeholder => "Username"%>
					<i class="icon-users form-control-feedback"></i>
				</div>

				<div class="form-group has-feedback">
					<label>Password</label>
					<%= f.password_field :password, class: 'form-control', :html => {type:'password', name: 'password', required: ""}, :placeholder => "Password" %>
					<i class="icon-lock form-control-feedback"></i>
				</div>

				<div class="row form-actions">

					<div class="col-xs-6">
						<button type="submit" class="btn btn-warning pull-right"><i class="icon-menu2"></i> Sign in</button>
					</div>
				</div>
			</div>
			<% end %>
	</div>
	<!-- /login wrapper -->
    <!-- Footer -->
		<div class="footer clearfix">
			<div class="pull-right">Simple Rails Admin Panel, created by Tasos Anesiadis, find me on <a href="https://github.com/roneen31"> Github</a></div>
		</div>
    <!-- /footer -->
</body>
</html>